// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "TouchScreen_horizontal.h"

#define NEW_TS_STRATEGE

static int sta_no = 0;
static	char *station_name = NULL;

Fl_Window *screen_window=(Fl_Window *)0;
Fl_Double_Window *screen_window2=(Fl_Double_Window *)0;
Fl_Wizard *sw_1=(Fl_Wizard *)0;
Fl_Wizard *wz_window_view=(Fl_Wizard *)0;
Fl_Group *cd_main_group=(Fl_Group *)0;
Fl_Group *cd_gp_live=(Fl_Group *)0;
Fl_Tile *key_request=(Fl_Tile *)0;
Fl_Tile *information=(Fl_Tile *)0;
Fl_Tile *lock=(Fl_Tile *)0;
Fl_Tile *start_station=(Fl_Tile *)0;
Fl_Tile *end_station=(Fl_Tile *)0;
Fl_Tile *current_station=(Fl_Tile *)0;
Fl_Tile *next_station=(Fl_Tile *)0;
Fl_Tile *open_door=(Fl_Tile *)0;
Fl_Tile *end_value=(Fl_Tile *)0;
Fl_Tile *start_value=(Fl_Tile *)0;
Fl_Tile *open_value=(Fl_Tile *)0;
Fl_Tile *next_value=(Fl_Tile *)0;
Fl_Tile *current_value=(Fl_Tile *)0;
Fl_Tile *pcu_recept=(Fl_Tile *)0;
Fl_Tile *pcu_value=(Fl_Tile *)0;
Fl_Wizard *sw_2=(Fl_Wizard *)0;
Fl_Tile *key_request_1 = (Fl_Tile *)0;
Fl_Tile *information_1 = (Fl_Tile *)0;
Fl_Group *cd_gp_intercomm=(Fl_Group *)0;
Fl_Wizard *cd_wz_window_view=(Fl_Wizard *)0;
int switchFlag;


int touch_screen_main() {
{  
	screen_window2 = new Fl_Double_Window(480, 320, "display");
	screen_window2->box(FL_BORDER_BOX);
    screen_window2->color(FL_FOREGROUND_COLOR);
    screen_window2->selection_color(FL_FOREGROUND_COLOR);
   {
   	 wz_window_view = new Fl_Wizard(0, 0, 480, 320);
   	 wz_window_view->box(FL_UP_BOX);
	{ 
	  cd_main_group = new Fl_Group(0, 0, 480, 320);
	  //cd_main_group->color((Fl_Color)246);
	  cd_main_group->hide();
	  { //key_request = new Fl_Tile(20, 20, 79, 25, "\350\257\267\346\217\222\345\205\245\351\222\245\345\214\231");
	  	key_request = new Fl_Tile(30, 30, 79, 25, "           \346\254\242\350\277\216\344\271\230\345\235\220\346\210\220\351\203\2757\345\217\267\347\272\277");
	 	key_request->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE |FL_ALIGN_WRAP));
		key_request->end();
	  } // Fl_Tile* key_request
	  { information = new Fl_Tile(30, 90, 87, 25, "\345\210\227\350\275\246\350\277\220\350\220\245\344\277\241\346\201\257");
	  	information->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE |FL_ALIGN_WRAP));
		information->end();
	  } // Fl_Tile* information
	  { lock = new Fl_Tile(240, 90, 55, 25);
	  	lock->align(Fl_Align(FL_ALIGN_WRAP));
		lock->end();
	  } // Fl_Tile* information
	  { start_station = new Fl_Tile(30, 145, 55, 25, "\350\265\267\347\202\271\347\253\231");
	    start_station->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE |FL_ALIGN_WRAP));
		start_station->end();
	  } // Fl_Tile* start_station
	  { end_station = new Fl_Tile(240, 145, 55, 25, "\347\273\210\347\202\271\347\253\231");
	    end_station->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE |FL_ALIGN_WRAP));
		end_station->end();
	  } // Fl_Tile* end_station
	  { current_station = new Fl_Tile(30, 200, 55, 25, "\345\275\223\345\211\215\347\253\231");
	    current_station->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE |FL_ALIGN_WRAP));
		current_station->end();
	  } // Fl_Tile* current_station
	  { next_station = new Fl_Tile(240, 200, 55, 25, "\344\270\213\344\270\200\347\253\231");
	    next_station->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE |FL_ALIGN_WRAP));
		next_station->end();
	  } // Fl_Tile* next_station
	  { open_door = new Fl_Tile(30, 255, 55, 25, "\345\274\200\351\227\250\344\276\247");
	    open_door->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE |FL_ALIGN_WRAP));
		open_door->end();
	  } // Fl_Tile* open_door
	  { start_value = new Fl_Tile(120, 145, 55, 25);
	 	start_value->align(FL_ALIGN_WRAP);
		start_value->end();
	  } // Fl_Tile* start_value
	  { end_value = new Fl_Tile(330, 145, 55, 25);
	 	end_value->align(FL_ALIGN_WRAP);
		end_value->end();
	  } // Fl_Tile* end_value
	  { current_value = new Fl_Tile(120, 200, 55, 25);
	  	current_value->align(FL_ALIGN_WRAP);
		current_value->end();
	  } // Fl_Tile* current_value
	  { next_value = new Fl_Tile(330, 200, 55, 25);
	  	next_value->align(FL_ALIGN_WRAP);
		next_value->end();
	  } // Fl_Tile* next_value
	  { open_value = new Fl_Tile(120, 255, 55, 25);
	  	open_value->align(FL_ALIGN_WRAP);
		open_value->end();
	  } // Fl_Tile* open_value
	  { pcu_recept = new Fl_Tile(240, 255, 55, 25);
	  	pcu_recept->align(FL_ALIGN_WRAP);
		pcu_recept->end();
	  } // Fl_Tile* pcu_request
	  { pcu_value = new Fl_Tile(310, 255, 55, 25);
	  	pcu_value->align(FL_ALIGN_WRAP);
		pcu_value->end();
	  } // Fl_Tile* pcu_request
	  cd_main_group->hide();
	  cd_main_group->end();
	  Fl_Group::current()->resizable(cd_main_group);
	}
	 wz_window_view->end();
   }
	wz_window_view->value(cd_main_group);
	screen_window2->end();
    screen_window2->resizable(screen_window);
  } // Fl_Window* screen_window
	Fl::visual(FL_DOUBLE|FL_INDEX);
    screen_window2->show();
#ifdef NEW_TS_STRATEGE
	while (Fl::wait())
	{
		if(switchFlag != 0)
		{
			  if(switchFlag == 1) ///<更新起始站
			  {
				  TouchScreenShowStationInfo(0);
				  switchFlag = 0;
			  }else if(switchFlag == 2) ///<显示
			  {
			  	  TouchScreenShowStationInfo(1);
				  switchFlag = 0;
			  }else if(switchFlag == 3)
			  {
				  TouchScreenShowPCUInfo();
				  switchFlag = 0;
			  }
			  else if(switchFlag == 4)
			  {
				  TouchScreenShowLockInfo();
				  switchFlag = 0;
			  }
			  else
			  {
				  switchFlag = 0;
			  }
		}
	}	  
#else
   return Fl::run();
#endif
}

void TouchScreenMain(int a, int b) {
    touch_screen_main();
}
